# -*- coding: utf-8 -*-
"""GB_Python-INTRO_Seminar-10 - EXAM_(task_44).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GaWH779Rj8HUWNrcbTWhe3CFi2-u5hc

# Задание 44
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

import random

lst = ['robot'] * 10

lst += ['human'] * 10

random.shuffle(lst)

data = pd.DataFrame({'whoAmI': lst})

data.head()
"""

import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10

random.shuffle(lst)

data = pd.DataFrame({'whoAmI': lst})
data.head()

#one hot вид сгенерированного списка с использованием функции get_dummies() библиотеки pandas
import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10

random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

pd.get_dummies(data['whoAmI'])

#one hot вид сгенерированного списка БЕЗ использованием функции get_dummies() библиотеки pandas
import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10

random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})


data.loc[data['whoAmI'] == 'human', 'human'] = '1'
data.loc[data['whoAmI'] != 'human', 'human'] = '0'
data.loc[data['whoAmI'] == 'robot', 'robot'] = '1'
data.loc[data['whoAmI'] != 'robot', 'robot'] = '0'

data[['human','robot']]